name: Deploy Angular App

on:
  push:
    branches:
      - master  # Monitorando a branch master para o push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Certifique-se de usar a versão 20 do Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --configuration production --base-href "/portfolio-landing-page/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master  # Usando a branch master
          publish_dir: ./dist/portfolio-landing-page  # Certifique-se de que o caminho de build está correto
          destination_dir: docs  # Publicar dentro da pasta /docs na branch master
