name: Deploy Angular App

on:
  push:
    branches:
      - master  # Ou a branch que você está monitorando

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Certifique-se de usar a versão correta do Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build:prod  # Usando o script customizado que inclui o base-href

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Publicando na branch gh-pages
          publish_dir: ./dist/portfolio-landing-page  # Certifique-se de que o caminho de build está correto
          destination_dir: docs  # Publicar dentro da pasta /docs na branch master
