name: Deploy Angular App

on:
  push:
    branches:
      - main  # A branch que vai disparar o workflow (use 'main' ou a branch que você preferir)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Certifique-se de usar a versão do Node.js correta

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/portfolio-landing-page  # Certifique-se de que este caminho está correto
