name: Deploy Angular App

on:
  push:
    branches:
      - main  # A branch que você está usando para disparar o workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # A versão correta do Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --configuration production --base-href "/portfolio-landing-page/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/portfolio-landing-page  # Certifique-se de que o caminho está correto
